LKS 3.0/LKS.Web/Models/ErrorViewModel.cs
using System;

namespace LKS.Web.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

LKS 3.0/LKS.Web/Controllers/AddedStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LKS.Data.Abstract;
using LKS.Data.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LKS.Web.Controllers
{
    public class AddedStudentController : Controller
    {
		IStudentRepository studentRepository;
		public AddedStudentController(IStudentRepository studentRepository)
		{
			this.studentRepository = studentRepository;
		}
        // GET: AddedStudent/Create
        public ActionResult Create()
        {
            //ViewBag.InstGroups = studentRepository.GetItems().Select(u => u.InstGroup).ToList();
            
            return View(); 
        }

        // POST: AddedStudent/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  ActionResult Create(Student student)//IFormCollection collection)
        {
                studentRepository.Create(student);
                return RedirectToAction("Create");
		}

        // GET: AddedStudent/Edit/5
        
    }
}

LKS 3.0/LKS.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LKS.Web.Models;

namespace LKS.Web.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult About()
		{
			ViewData["Message"] = "Your application description page.";

			return View();
		}

		public IActionResult Contact()
		{
			ViewData["Message"] = "Your contact page.";

			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

LKS 3.0/LKS.Web/Controllers/StudentListController.cs
using LKS.Data.Abstract;
using LKS.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Linq;

namespace LKS.Web.Controllers
{
	public class StudentListController : Controller
	{
		//private const int pageSize = 20;
		//IStudentRepository studentRepository;
		//ICycleRepository cycleRepository;
		//public StudentListController(IStudentRepository studentRepository, ICycleRepository cycleRepository)
		//{
		//	this.cycleRepository = cycleRepository;
		//	this.studentRepository = studentRepository;
		//}

		//public IActionResult Index()
		//{
		//	//var model = studentRepository.GetItems().ToList();//todo
		//	//ViewBag.pageSize = pageSize;
		//	//return View(model);
		//}

		//[HttpPost]
		//public JsonResult GetStudents([FromBody]Newtonsoft.Json.Linq.JObject data)
		//{
		//	//var students = studentRepository.GetItems().Include(ob => ob.Troop).ThenInclude(ob => ob.Cycle).AsQueryable();
		//	//int page;
		//	//string sort = data.GetValue("sort")?.ToString(),
		//	//	filter = data.GetValue("filter")?.ToString(),
		//	//	filterCol = data.GetValue("filterCol")?.ToString(),
		//	//	cycle = data.GetValue("selectCycle")?.ToString(),
		//	//	troop = data.GetValue("selectTroop")?.ToString();
		//	//if(!String.IsNullOrWhiteSpace(cycle) && cycle != "#")
		//	//{
		//	//	students = students.Where(ob => ob.Troop.Cycle.Number == cycle);
		//	//}
		//	//if (!String.IsNullOrWhiteSpace(troop))
		//	//{
		//	//	students = students.Where(ob => ob.Troop.NumberTroop == troop);
		//	//}
		//	//if (!String.IsNullOrWhiteSpace(filter) && !String.IsNullOrWhiteSpace(filterCol))
		//	//{
		//	//	students = FilterStudents(students, filter, filterCol);
		//	//}
		//	//if (Int32.TryParse(data.GetValue("page").ToString(), out page) && sort != null)
		//	//{

		//	//	students = SortStudents(students, sort);
		//	//	int count = students.Count();
		//	//	students = students.Skip((page - 1) * pageSize).Take(pageSize);
		//	//	return Json(new
		//	//	{
		//	//		ok = true,
		//	//		count,
		//	//		students = students.ToList()
		//	//	});
		//	//}
		//	//return Json(new { ok = false });
		//}

		
		//public JsonResult GetCycle(string cycleId = null)
		//{
		//	//if (cycleId == null || cycleId == "#")
		//	//{
		//	//	return Json(cycleRepository.GetItems().Select(p => new
		//	//	{
		//	//		id = "cycle-" + p.Id,
		//	//		parent = "#",
		//	//		text = p.Number,
		//	//		children = true,
		//	//	}));
		//	//}
		//	//else
		//	//{
		//	//	string correctCycleId = cycleId.Replace("cycle-", "");
		//	//	return Json(cycleRepository.GetItems().Include(ob => ob.Troops).FirstOrDefault(ob => ob.Id == correctCycleId)?.Troops.Select(p => new
		//	//	{
		//	//		id = "trop-" + p.Id,
		//	//		parent = cycleId,
		//	//		text = p.NumberTroop,
		//	//		children = false,
		//	//	}));
		//	//}
		//}

		//private IQueryable<Student> FilterStudents(IQueryable<Student> students, string filterText, string filterColumn)
		//{
		//	filterText = filterText.ToLower();
		//	filterColumn = filterColumn.ToLower();
		//	switch (filterColumn)
		//	{
		//		case "middlename": return students.Where(ob => ob.MiddleName.ToLower().Contains(filterText));
		//		case "firstname": return students.Where(ob => ob.FirstName.ToLower().Contains(filterText));
		//		case "lastname": return students.Where(ob => ob.LastName.ToLower().Contains(filterText));
		//		case "numtroop": return students.Where(ob => ob.Troop.NumberTroop.ToLower().Contains(filterText));
		//		default: return students;
		//	}
		//}
		//private IQueryable<Student> SortStudents(IQueryable<Student> students, string sort)
		//{
		//	sort = sort.ToLower();
		//	switch (sort)
		//	{
		//		case "middlename": return students.OrderBy(ob => ob.MiddleName);
		//		case "middlenamedesc": return students.OrderByDescending(ob => ob.MiddleName);
		//		case "firstname": return students.OrderBy(ob => ob.FirstName);
		//		case "firstnamedesc": return students.OrderByDescending(ob => ob.FirstName);
		//		case "lastname": return students.OrderBy(ob => ob.LastName);
		//		case "lastnamedesc": return students.OrderByDescending(ob => ob.LastName);
		//		case "numtroop": return students.OrderBy(ob => ob.NumTroop);
		//		case "numtroopdesc": return students.OrderByDescending(ob => ob.NumTroop);
		//		default: return students.OrderBy(ob => ob.NumTroop);
		//	}
		//}

		//public OkResult createStudents()
		//{
		//	var troops = cycleRepository.GetItems().Include(ob => ob.Troops).FirstOrDefault()?.Troops;
		//	System.Collections.Generic.List<Student> students = new System.Collections.Generic.List<Student>();
		//	for(int i = 0; i < 10000; i++)
		//	{
		//		students.Add(new Student
		//		{
		//			FirstName = "fName" + i,
		//			LastName = "lName" + i,
		//			MiddleName = "mName" + i,
		//			TroopId = "1"
		//		});
		//	}
		//	studentRepository.CreateRange(students);
		//	return new OkResult();
		//}
	}
}

LKS 3.0/LKS.Web/Controllers/TroopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LKS.Data.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace LKS.Web.Controllers
{
    public class TroopController : Controller
    {
		ITroopRepository troopReposotory;

		public TroopController(ITroopRepository troopRepository)
		{
			this.troopReposotory = troopRepository;
		}
        public IActionResult Create()
        {
            return View();
        }
    }
}

LKS 3.0/LKS.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

LKS 3.0/LKS.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LKS 3.0/LKS.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

LKS 3.0/LKS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LKS.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LKS.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - LKS.Web</p>
        </footer>
    </div>
</body>
</html>

LKS 3.0/LKS.Web/Views/Shared/_LayoutAdd.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>
    @RenderSection("Scripts", required: false)
</head>
<body>
    <!--меню-->
    <ul class="nav nav-tabs bg-dark">
        <li class="nav-item">
            <a class="nav-link active" href="#">Active</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Another link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li>
    </ul>
    <!--основной контент-->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>© 2018 - LKS-3.0</p>
        </footer>
    </div>
</body>
</html>

LKS 3.0/LKS.Web/Views/StudentList/Index.cshtml
@model IEnumerable<LKS.Data.Models.Student>

@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
<script type="text/javascript" src="~/js/StudentList.js"></script>
<link rel="stylesheet" href="~/css/StudentList.css" />

<input id="pageSizeConst" type="hidden" value="@ViewBag.pageSize" />
<div class="student-container">
    <div class="nav">
        <ul id="jstree"></ul>
    </div>
    <div class="content">
        <table class="table">
            <thead>
                @* !! При изменении шапки надо внести изменение в тело таблицы, а так-же в функцию pageClick *@
                <tr>
                    <th nowrap>
                        <span onclick="javascript:setSort('MiddleName')" style="background: url(/images/sort.png) no-repeat; width: 25px; height: 25px; cursor: pointer;"></span>
                        <p class="input-container">
                            <input type="text" id="MiddleNameFilter" data-id="MiddleName" />
                            <label for="MiddleNameFilter" unselectable="on">@Html.DisplayNameFor(model => model.MiddleName)</label>
                        </p>
                    </th>
                    <th nowrap>
                        <p class="input-container">
                            <input type="text" id="FirstNameFilter" data-id="FirstName" />
                            <label for="FirstNameFilter" unselectable="on">@Html.DisplayNameFor(model => model.FirstName)</label>
                        </p>
                        @*<a href="javascript:setSort('FirstName')">
                                @Html.DisplayNameFor(model => model.FirstName)
                                <span id="FirstNameDescRow" style="display:none">▼</span>
                                <span id="FirstNameRow" style="display:none">▲</span>
                            </a>
                            <div class="filter"><input type="text" id="FirstNameFilter"  data-id="FirstName"/> <button onclick="javascript:setFilter('FirstName')"></button></div>*@
                    </th>
                    <th nowrap>
                        <p class="input-container">
                            <input type="text" id="LastNameFilter" data-id="LastName" />
                            <label for="LastNameFilter" unselectable="on">@Html.DisplayNameFor(model => model.LastName)</label>
                        </p>
                        @*<a href="javascript:setSort('LastName')">
                                @Html.DisplayNameFor(model => model.LastName)
                                <span id="LastNameDescRow" style="display:none">▼</span>
                                <span id="LastNameRow" style="display:none">▲</span>
                            </a>
                            <div class="filter"><input type="text" id="LastNameFilter"  data-id="LastName"/> <button onclick="javascript:setFilter('LastName')"></button></div>*@
                    </th>
                    <th nowrap>
                        <p class="input-container">
                            <input type="text" id="NumTroopFilter" data-id="NumTroop" />
                            <label for="NumTroopFilter" unselectable="on">@Html.DisplayNameFor(model => model.NumTroop)</label>
                        </p>
                        @*<a href="javascript:setSort('NumTroop')">
                                @Html.DisplayNameFor(model => model.NumTroop)
                                <span id="NumTroopDescRow" style="display:none">▼</span>
                                <span id="NumTroopRow">▲</span>
                            </a>
                            <div class="filter"><input type="text" id="NumTroopFilter" data-id="NumTroop" /> <button onclick="javascript:setFilter('NumTroop')"></button></div>*@
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.Rank)
                    </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.SpecialityName)
                    </th>
                    <th>
                        <p class="input-container">
                            <input type="text" id="input-group" />
                            <label for="input-group" unselectable="on">@Html.DisplayNameFor(model => model.InstGroup)</label>
                        </p>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Kurs)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Faculty)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SpecInst)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ConditionsOfEducation)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AvarageScore)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.YearOfAddMAI)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.YearOfEndMAI)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.YearOfAddVK)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.YearOfEndVK)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NumberOfOrder)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateOfOrder)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Rectal)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Birthday)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlaceBirthday)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nationality)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Citizenship)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HomePhone)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MobilePhone)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlaceOfResidence)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PlaceOfRegestration)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Military)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FamiliStatys)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.School)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Two_MobilePhone)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.VuzName)
                        </th>*@
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div id="pagingBox">
        </div>
    </div>
</div>
<a asp-area="" asp-controller="AddedStudent" asp-action="Create" role="button" class="btn btn-primary">Добавить нового студента</a>

LKS 3.0/LKS.Web/Views/Troop/Create.cshtml
@model LKS.Data.Models.Troop

<style>
    .modal-box {
        margin: 30px;
        box-shadow: 0 10px 28px rgba(0,0,0,0.25), 0 0px 10px rgba(0,0,0,0.22);
        border-radius: 10px;
        background-color: white;
        padding: 30px;
        width: auto;
        min-width: 400px;
        min-height: 300px;
        display: flex;
        align-items: center;
        justify-content: center;
        border: solid 0.3px black;
    }

        .modal-box div.form-group.input-container {
            width: 100px;
            height: 30px;
            position: relative;
            margin: 0;
            margin-top:40px;
        }

            .modal-box div.form-group.input-container label {
                position: absolute;
                cursor: text;
                transform: translateY(-10px);
                transition: transform 0.3s ease;
                left: 0;
                bottom: -10px;
            }

            .modal-box div.form-group.input-container input {
                width: 100%;
                transition: 0.6s;
                border: none;
                border-bottom: 1px solid #d8d8d8;
                position: absolute;
                bottom: 0px;
                background-color: transparent;
                font-family: PFEncoreSansPro;
                font-size: 14px;
                font-weight: normal;
                font-style: normal;
                font-stretch: normal;
                line-height: 1.43;
                letter-spacing: 0.2px;
                color: #1b1e2d;
            }

                .modal-box div.form-group.input-container input:focus {
                    outline: none;
                    border-bottom: 1px solid #28a2a2;
                }

            .modal-box div.form-group.input-container.animation label {
                transform: translateY(-35px);
                height: 12px;
                font-size: 12px;
                color: #aaaaaa;
            }
</style>

<script type="text/javascript">
    $(function () {
        $('.input-container>input').focus(function () {
            $(this).parent().addClass("animation");
        });
        $('.input-container>input').blur(function () {
            if (!$(this).val()) {
                $(this).parent().removeClass("animation");
            }
        })
    });
</script>

<div class="modal-box">
    <div>
        <h4>Создание взвода</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                   
                    <div class="form-group input-container">
                        <label asp-for="PrepodId" >Преподаватель</label>
                        <input asp-for="PrepodId" />
                        <span asp-validation-for="PrepodId" class="text-danger"></span>
                    </div>
                    <div class="form-group input-container">
                        <label asp-for="NumberTroop" >Номер взвода</label>
                        <input asp-for="NumberTroop" />
                        <span asp-validation-for="NumberTroop" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input asp-for="SboriTroop" /> @Html.DisplayNameFor(model => model.SboriTroop)
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>